### ISSUE TITLE
Implement geolocation support

### ISSUE THREAD

**Issue by cratelyn** [fastly/Viceroy#10]
As mentioned in the project's [README](https://github.com/fastly/Viceroy/blob/main/README.md#limitations), we do not currently support all of the features provided by Compute@Edge's production environment. One of these missing features is geolocation.

This is a tracking issue to document ongoing work to implement this support.

**Comment by bbutkovic** [comment]
Hey, I started work on this over at #165. I'm open to any code/feature suggestions so please let me know if I'm headed in the right direction.

**Comment by aturon** [comment]
Thank you so much for picking this up @bbutkovic! I'll get some commentary going on the PR itself.
