### ISSUE TITLE
Implement edge dictionary support

### ISSUE THREAD

**Issue by cratelyn** [fastly/Viceroy#11]
As mentioned in the project's [README](https://github.com/fastly/Viceroy/blob/main/README.md#limitations), we do not currently support all of the features provided by Compute@Edge's production environment. One of these missing features is Edge Dictionaries.

This is a tracking issue to document ongoing work to implement this support.

**Comment by JakeChampion** [comment]
The limitations section in the readme was removed in [commit ba3d8a4](https://github.com/fastly/Viceroy/commit/ba3d8a46a22670d89bf8b2f5dff22d266800d2cd#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)

This is what it said:

> ## Limitations
> 
> At the moment, Viceroy does not support the full Compute@Edge API. In
> particular:
> 
> * GeoIP is unsupported.
> * Dictionaries are unsupported.
> * Caching directives are ignored; no caching is ever performed.
> * Information about the TLS connection from the client is not available.
>
