### ISSUE TITLE
`fastly_http_req::auto_decompress_response_set` has not been defined (`fastly=v0.8.1`)

### ISSUE THREAD

**Issue by Integralist** [fastly/Viceroy#110]
Please refer to the original report opened by @jar3k in the Fastly CLI issue tracker: https://github.com/fastly/cli/issues/496

**Comment by jar3k** [comment]
Thanks a lot for solving this! :)

**Comment by mgattozzi** [comment]
No problem @jar3k we'll still need to get a point release out in the meantime, but you can run your wasm locally with the main branch till then. Do note it doesn't implement that function yet, but it didn't seem like you were using it :)

**Comment by mgattozzi** [comment]
@jar3k we just released the new point release and so running `fastly compute serve` should work exactly as you'd expect now!

**Comment by jar3k** [comment]
> @jar3k we just released the new point release and so running `fastly compute serve` should work exactly as you'd expect now!

Wonderful! Thanks!

**Comment by cratelyn** [comment]
a brief follow up: today we've released an additional release, [v0.2.9](https://github.com/fastly/Viceroy/releases/tag/v0.2.9), which contains some additional fixes related to this problem. thank you for raising this issue @jar3k!
