### ISSUE TITLE
auto_decompress_response_set has not yet been implemented in Viceroy

### ISSUE THREAD

**Issue by StarpTech** [fastly/Viceroy#115]
Hello, we run into

```
 panicked at 'not implemented: auto_decompress_response_set has not yet been implemented in Viceroy', /home/starptech/.cargo/registry/src/github.com-1ecc6299db9ec823/viceroy-lib-0.2.8/src/wiggle_abi/req_impl.rs:476:9
```

```rs
     // Build client request
        let req = hyper::Request::builder()
            .method(Method::POST)
            .uri("http://example.com")
            .header("authorization", "bearer 123")
            .header("content-type", "application/json")
            .body(Body::from(serde_json::to_string(client_json_body).unwrap()))
            .unwrap();

        // Fire request
        let response = viceroy::handle_request(req, url).await.unwrap();
```

when upgrading from "fastly: 0.8.0" to "fastly: 0.8.1"

It will internally update

```
[[package]]
name = "fastly-shared"
version = "0.8.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "a50fae8c678779e8dcd18e36f9982d09c706764e8976c542fd53193a62d83727"
dependencies = [
 "bitflags",
 "http",
 "thiserror",
]

[[package]]
name = "fastly-sys"
version = "0.8.1"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "afcf0f870a0c9ac8166b0797a9391e5df81b7b5cc13b53b4d305e0b1368801d4"
dependencies = [
 "bitflags",
 "fastly-shared 0.8.1",
]
```

It was introduced in https://github.com/fastly/Viceroy/commit/fee8165aa6396a348b946a31bc658acb291e8594

Related: https://github.com/fastly/cli/issues/496

**Comment by cratelyn** [comment]
hello @StarpTech! could you check which version of Viceroy that you are running? fee8165 (_see #113_), and the subsequent `0.2.8` release (_see #114_) should have _fixed_ this issue, which was raised by changes in the `0.8.1` SDK release.

could you try running `viceroy --version` to confirm that you are seeing this even when running `0.2.8`?

**Comment by JakeChampion** [comment]
Howdy @cratelyn - I'm also seeing the same issue when using Viceroy version 0.2.8 and Fastly 0.8.1

I think this could be fixed removing the `unimplemented!` call in the below function:
https://github.com/fastly/Viceroy/blob/264e71ee048fc8a437a55ab4ba04a9ef908b6bf0/lib/src/wiggle_abi/req_impl.rs#L471-L478

**Comment by cratelyn** [comment]
ah! i see, this _is_ indeed a problem with that stub. upon inspecting the `fastly` crate, i see that this `auto_decompress_response_set` function is called in a common code path. (_here: https://docs.rs/fastly/latest/src/fastly/http/request.rs.html#2039_)

i believe you are correct @JakeChampion, the solution here is probably to stub this out with an `Ok(())` no-op for now, instead of the `unimplemented!` calls we can use for other as-yet unimplemented hostcalls.

**Comment by aturon** [comment]
A suggestion: we could make the behavior dependent on _which_ `ContentEncodings` are present, i.e. use `unimplemented!()` only if the call is trying to use gzip, until that piece is implemented.

**Comment by JakeChampion** [comment]
I've created a pull-request which implements the suggestion made by @aturon ☺️ 
https://github.com/fastly/Viceroy/pull/116

**Comment by cratelyn** [comment]
cc: @StarpTech @JakeChampion 

a new v0.2.9 release has been [published](https://github.com/fastly/Viceroy/releases/tag/v0.2.9) that addresses this issue. thank you for bringing this to our attention, and to Jake for implementing the fix! you can also find the new versions of [`viceroy-lib`](https://crates.io/crates/viceroy-lib/0.2.9) and [`viceroy`](https://crates.io/crates/viceroy/0.2.9) on crates.io.
