### ISSUE TITLE
.config/fastly/viceroy: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by alameth** [fastly/Viceroy#120]
**Version**

```
Fastly CLI version 1.5.0 (0d495f7)
Built with go version go1.17.6 linux/amd64
Viceroy version: viceroy 0.2.9

```
**What happened**

```
$ fastly compute serve --addr "127.0.0.1":7880 --skip-build
Initializing...
Fetching latest Viceroy release...
Running local server...

/home/cgutekunst/.config/fastly/viceroy: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/cgutekunst/.config/fastly/viceroy)

ERROR: error during execution process:

/home/cgutekunst/.config/fastly/viceroy: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/cgutekunst/.config/fastly/viceroy).

If you believe this error is the result of a bug, please file an issue: https://github.com/fastly/cli/issues/new?labels=bug&template=bug_report.md
```

System lsb:
```
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=19.3
DISTRIB_CODENAME=tricia
DISTRIB_DESCRIPTION="Linux Mint 19.3 Tricia"

```
I'm _guessing_ that the prebuilt (downloaded) version of Viceroy was built on Ubuntu 20; I'm on Mint 19.3, which is wrapper around Ubuntu 18.04 LTS.

**WORKAROUND**

Built viceroy from source and hard linked it from cargo/.bin to .config/fastly.

**Comment by Integralist** [comment]
The user @lyrixx also had [the exact same issue](https://github.com/fastly/cli/issues/526) and workaround.

**Comment by alameth** [comment]
Upgrading the version of GLIBC on an LTS distro is hard, deliberately so; locally compiling viceroy was easy. :-) Thanks for the forward; this was just my best guess as to the correct team.

**Comment by Integralist** [comment]
> Upgrading the version of GLIBC on an LTS distro is hard, deliberately so; locally compiling viceroy was easy. :-) 

Ah, yeah I guess I'm suggestion was a wee bit ..._optimistic_ 😄 

> Thanks for the forward; this was just my best guess as to the correct team.

No problem 🙂

**Comment by mgattozzi** [comment]
Since there's a workaround for this issue, I'm going to close this for now and have it be superseded by #174 so that we can avoid this issue in the future. Thanks for taking the time to open up the issue @alameth

**Comment by kanevbg** [comment]
same issue on rhel 8
