### ISSUE TITLE
How to run wasm tests?

### ISSUE THREAD

**Issue by StarpTech** [fastly/Viceroy#151]
Hi, I didn't figure out the right build configuration but I could manage to run the test against my host target. How can we run tests with the WASM target?

main.rs
```rs
 fn it_works() {
        let result = 2 + 2;
        assert_eq!(result, 4);
    }
```

`cargo test` result in

```
    Finished test [unoptimized + debuginfo] target(s) in 0.33s
     Running unittests (/home/starptech/p/test/target/wasm32-wasi/debug/deps/test-2590a4c954364fd1.wasm)
/home/starptech/p/test/target/wasm32-wasi/debug/deps/test-2590a4c954364fd1.wasm: 1: Syntax error: end of file unexpected
```

can be fixed by specifying a different build and test target

.cargo/config.toml
```
[build]
target = "wasm32-wasi"

[profile.test]
inherits = "release"
[profile.test.build-override]
target = ""
```

and then run `cargo test --target x86_64-unknown-linux-gnu -- --show-output`.

I think this is something we should document. Maybe you also have a better way to configure that without specifying an explicit target.

Repro: https://github.com/fastly/compute-starter-kit-rust-default

**Comment by GeeWee** [comment]
I've had help using `cargo wasi test` as well.

**Comment by StarpTech** [comment]
@GeeWee nice, I'll give it a shot.

**Comment by yannh** [comment]
Any success here? It is failing for me with issues such as "1: unknown import: `fastly_http_body::new` has not been defined". My (_very_ limited) understanding is that the ABI defined in WITX here https://github.com/fastly/Viceroy/blob/main/lib/compute-at-edge-abi/compute-at-edge.witx  defines functions that are not part of the base WASI?  Is it possible to run cargo wasi test while using the ABI created & used by viceroy? 

I've been searching for a way to run unit-tests in wasm for Compute@Edge for quite a long time, any hint would be most welcome <3

**Comment by JakeChampion** [comment]
> Any success here? It is failing for me with issues such as "1: unknown import: `fastly_http_body::new` has not been defined". My (_very_ limited) understanding is that the ABI defined in WITX here https://github.com/fastly/Viceroy/blob/main/lib/compute-at-edge-abi/compute-at-edge.witx defines functions that are not part of the base WASI? Is it possible to run cargo wasi test while using the ABI created & used by viceroy?
> 
> I've been searching for a way to run unit-tests in wasm for Compute@Edge for quite a long time, any hint would be most welcome <3

I think this feature is being worked on in https://github.com/fastly/Viceroy/pull/211 by @itsrainy 🙂

**Comment by cratelyn** [comment]
@StarpTech, #211 has now landed, permitting unit tests to be run in Wasm now thanks to @itsrainy :heart: see the `README.md` section here: https://github.com/fastly/viceroy#usage-as-a-test-runner

i'm going to close this as completed now :sparkles:
