### ISSUE TITLE
Ensure fastly request limits

### ISSUE THREAD

**Issue by StarpTech** [fastly/Viceroy#152]
Hi, in order to simulate the fastly platform better, it would be great to implement the limits in https://docs.rs/fastly/0.7.3/fastly/limits/index.html As a user, I'd like to test against these cases.

**Comment by aspires** [comment]
@StarpTech these limits are enforced in the SDK, so they should already be supported in Viceroy. Are you getting different results when you test?

**Comment by JakeChampion** [comment]
@StarpTech, to add a bit more onto what Austin has said, as well as the limits being defined in the SDKs, Viceroy does also implement some of the limits itself when necessary, the below two files contain some of the limits Viceroy implements:
- https://github.com/fastly/Viceroy/blob/627e368971a3c396402a7805800fbc6e9a4f9a0a/lib/src/config/limits.rs#L1-L4
- https://github.com/fastly/Viceroy/blob/45c24063fa74b7871ccff53ddf93986675772ccd/lib/src/wiggle_abi/headers.rs#L10

**Comment by StarpTech** [comment]
Hi, thanks for the Infos! I just want to be sure 👍
