### ISSUE TITLE
Backends are address+port, not URIs

### ISSUE THREAD

**Issue by acw** [fastly/Viceroy#157]
In the current implementation, we implement backends as pointers to URIs, and they shouldn't be. In point of fact, they should only be an address (v4, v6, domain) plus port.

This is not a huge issue, as long as we don't expose and test the fact that they're URIs to users, but it turns out that we do. Note the `upstream` test, in particular, which registers backends with paths and validates that they're handled correctly. We should actually probably do the opposite, even if we choose to still represent things as URIs under the hood.

**Comment by aturon** [comment]
This was intentional, in part because we use the path component for path prefixing, described [here](https://developer.fastly.com/reference/compute/fastly-toml/#backends).

**Comment by acw** [comment]
Welp, today several Adams learned.
