### ISSUE TITLE
:warning: address github actions deprecation warnings

### ISSUE THREAD

**Issue by cratelyn** [fastly/Viceroy#193]
these deprecation warnings were observed while publishing 0.3.1, in #191. 

```
build (stable, ubuntu-latest, arm64)Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout, actions-rs/toolchain, olegtarasov/get-tag, actions-rs/cargo, softprops/action-gh-release, actions/checkoutShow less
build (stable, ubuntu-latest, arm64)The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

**Comment by itsrainy** [comment]
#197 fixed most of these deprecations. The one holdout is `softprops/action-gh-release`, which we could probably swap out for a more actively maintained action, though none of the ones I've found have releases in the past year. 

I think we could also get rid of the dependency and use `hub` directly similar to [what this action does](https://github.com/elgohr/Github-Release-Action/blob/main/entrypoint.sh), though I haven't poked at that yet.

**Comment by itsrainy** [comment]
`softprops/action-gh-release` has since released a new minor version, so we are no longer getting deprecation warnings on releases. (ex: https://github.com/fastly/Viceroy/actions/runs/3970141112)
