### ISSUE TITLE
Add `publish.rs` to top-level workspace

### ISSUE THREAD

**Issue by cratelyn** [fastly/Viceroy#20]
Today, we have a helper script to check that all of the packages in the workspace are publishable. This script was heavily inspired from a similar facility in `wasmtime`, which goes out of its way to avoid incurring any dependencies.

In conversation with @aturon however, we agreed that there are some benefits to allowing dependencies to exist. For example, the code used to parse out the `Cargo.toml` manifest is a bit ungainly. Additionally, we can use something like `clap` to handle parsing out command-line options.

**Comment by mgattozzi** [comment]
@cratelyn I'm going through and triaging issues and I think we can close this one given we have the script available. Is that correct or is there more functionality we want here?

https://github.com/fastly/Viceroy/blob/main/scripts/publish.rs

**Comment by cratelyn** [comment]
i'm content to close this. while the issue itself isn't addressed, this is a very low priority and probably not worth the effort today.
