### ISSUE TITLE
No release available for Windows i386

### ISSUE THREAD

**Issue by kailan** [fastly/Viceroy#200]
A customer reported that they were unable to use Viceroy on Windows i386.

The Fastly CLI does support win i386, so they were able to install the CLI, but running `fastly compute serve` failed as it was unable to fetch a matching Viceroy release from GitHub.

In the meantime this has been worked around by having the customer clone and build Viceroy themselves.

**Comment by pchickey** [comment]
Wasmtime doesn't actually support i386, so there is no way to make Viceroy work on that platform. The fact that it built at all for i386 is a bug, and we need to fix that.

The Fastly CLI will have to report an error that `fastly compute serve` doesn't work on i386.

**Comment by Integralist** [comment]
@kailan https://github.com/fastly/cli/pull/753
