### ISSUE TITLE
Rework CLI interface to include subcommands

### ISSUE THREAD

**Issue by itsrainy** [fastly/Viceroy#222]
Follow-up from https://github.com/fastly/Viceroy/pull/211.

There are more details in the comments on that PR, but the gist is:
- Make the run and serve functionality accessibly through `run` and `serve` subcommands
- The respective args for these subcommands should be enforced (ie. passing `--addr` shouldn't be allowed with the `run` subcommand)
- Maintain compatibility with the Fastly CLI (probably by making `serve` the default behavior)
- Remove the `quiet` flag and have `-v0` mean quiet. The default for `serve` mode should be  -v1 to align with the current behavior and the default for `run` mode should be -v0

**Comment by jameysharp** [comment]
As far as I can tell, this issue was completed when #229 merged, so I'm closing it.
