### ISSUE TITLE
Create a new folder on fastly compute init

### ISSUE THREAD

**Issue by JonathanSpeek** [fastly/Viceroy#263]
Many CLI's, when creating or init-ing a new project will create the directory for you. Would be great to have that as default so I don't have to 
```bash
mkdir project-name
cd project-name
fastly compute init
```
<img width="1089" alt="image" src="https://github.com/fastly/Viceroy/assets/11696256/4764f5be-369c-4fcf-8dab-ed34482be570">

Ideally it'd create a new directory using the project name it prompts for:
![CleanShot 2023-05-12 at 12 00 12@2x](https://github.com/fastly/Viceroy/assets/11696256/60e5ba4f-e206-4978-bf69-b4df7c416478)

**Comment by pchickey** [comment]
I believe this issue belongs over in https://github.com/fastly/cli

**Comment by JonathanSpeek** [comment]
Closing out and moving to the appropriate repo
