### ISSUE TITLE
0.9.0 Breaks concurrency

### ISSUE THREAD

**Issue by dbraley** [fastly/Viceroy#321]
Hello! A number of our engineers use viceroy through the fastly-cli for local development. This morning, a number of them were upgraded to v0.9.0 and immediately had their environments stop working. It seems that any request that is made concurrently with another ongoing request is getting the following error:
```
thread ‘tokio-runtime-worker’ panicked at lib/src/execute.rs:282:27:
failed to run guest: Error instantiating WebAssembly: maximum concurrent memory limit of 1 reached
```
I seem to recall it being 100 at some point in time, when we had to throttle certain types of requests, if that helps. I suspect it's a configurable value, but have no idea where it is configured.

I have confirmed that if I use viceroy v0.8.1 this does not happen.

**Comment by elliottt** [comment]
This was introduced with the wasmtime 13.0.0 upgrade: the total number of memories configured in the pooling allocator should have matched the maximum number of core instances.
