### ISSUE TITLE
Update Wasmtime

### ISSUE THREAD

**Issue by acme** [fastly/Viceroy#360]
Viceroy currently [uses Wasmtime version 13.0.0](https://github.com/fastly/Viceroy/blob/main/Cargo.toml#L42). 

Wasmtime has [released a number of versions](https://github.com/bytecodealliance/wasmtime/releases) since then (currently 19.0.2) and it would be great to incorporate these improvements.

**Comment by kpfleming** [comment]
Addressed by #366.
