### ISSUE TITLE
Package `README.md` with `viceroy`

### ISSUE THREAD

**Issue by cratelyn** [fastly/Viceroy#46]
See also #41, and #45.

We should package this project's `README.md` with the `viceroy` crate, so that the helpful information contained within is visible to people visiting the project on crates.io! :package:

**Comment by djKooks** [comment]
Hello @cratelyn 
Could you check https://github.com/fastly/Viceroy/pull/118 ?

**Comment by cratelyn** [comment]
hello @djKooks! sure thing, and thank you for opening that PR :smile_cat: :trophy:

**Comment by cratelyn** [comment]
this is now fixed via #118. hooray! :sparkler:
