### ISSUE TITLE
Broaden platform support on both CI and releases

### ISSUE THREAD

**Issue by aturon** [fastly/Viceroy#57]
The Fastly CLI supports some platforms that Viceroy releases don't currently cover, such as arm64. We should add these platforms to both CI and release automation, and make sure the CLI can distribute the new binaries.

**Comment by aturon** [comment]
Testing on ARM is difficult because GitHub actions don't include ARM hosts, so testing requires cross-compilation and emulation. It would probably make sense to borrow from [wasmtime's CI](https://github.com/bytecodealliance/wasmtime/blob/main/.github/workflows/main.yml).

**Comment by kpfleming** [comment]
I'll tackle this now, as there are Linux+arm64 runners available in GitHub Actions.

**Comment by kpfleming** [comment]
Ahh never mind, this already got done :-) Releases include binaries for macOS+arm64 and Linux+arm64.
