### ISSUE TITLE
Instrument and emit stats on program wall clock duration

### ISSUE THREAD

**Issue by cratelyn** [fastly/Viceroy#76]
Fastly's UI provides stats on the total wall clock of a Compute@Edge program running in production. Viceroy should emit information about the wall clock duration of a single instance execution, so that users can reason about the behavior of their program in production.

* see also #77.
* see also #78.

**Comment by cratelyn** [comment]
cc: @djKooks, i was guessing based on your activity in #118 and #63 that you were looking for good starter issues in this repository. this issue might be a good one to pick up, if you are interested!

you can see where we currently log how much heap space was used by a Wasm program, here: https://github.com/fastly/Viceroy/blob/main/lib/src/execute.rs#L279-L282

we could use [`Instant::now`](https://doc.rust-lang.org/std/time/struct.Instant.html#method.now) and it's `duration_since` method to find the time elapsed before/after instantiating and running the program. then, a call to [`tracing::info!`](https://docs.rs/tracing/latest/tracing/macro.info.html#examples) should let us emit a log message showing the total wall clock duration. :slightly_smiling_face: 

feel free to ping me if you have any further questions :bowing_woman:

**Comment by djKooks** [comment]
@cratelyn great thanks! I'll look on it 🙏

**Comment by djKooks** [comment]
@cratelyn sorry, I'm middle in research, so want to ask some basic question.

It should be the task to emit the CPU/RAM usage. So before going on, could you let me know how can I visualize (through cli) the stats which is currently being supported?

**Comment by djKooks** [comment]
@cratelyn for now I've saw
```
Jan 28 21:42:57.618  INFO Listening on http://127.0.0.1:7878
Jan 28 21:43:04.845  INFO request{id=0}: handling request GET http://127.0.0.1:7878/
Jan 28 21:43:04.855  INFO request{id=0}: request completed using 1.4 MB of WebAssembly heap
```
by running `Default starter for Rust` in build.

So the purpose for task is to display RAM usage, CPU time in this log?

**Comment by cratelyn** [comment]
> @cratelyn for now I've saw
> 
> ```
> Jan 28 21:42:57.618  INFO Listening on http://127.0.0.1:7878
> Jan 28 21:43:04.845  INFO request{id=0}: handling request GET http://127.0.0.1:7878/
> Jan 28 21:43:04.855  INFO request{id=0}: request completed using 1.4 MB of WebAssembly heap
> ```
> 
> by running `Default starter for Rust` in build.
> 
> So the purpose for task is to display RAM usage, CPU time in this log?

hi @djKooks, thank you for your patience, it looks like you found the right test to run. for reference, you can also use `--nocapture` to show logs when running tests, like so:

```sh
; cargo test -p viceroy request_works -- --nocapture
```

that logs at the `TRACE` level, so you'll see many more events, but the `INFO` events shown above will be shown. this should be a helpful way to see any new logs you add.

> So the purpose for task is to display RAM usage, CPU time in this log?

#78 and #79 cover RAM and CPU time, respectively. this issue is specifically focused on showing how long it took for the Wasm binary to finish running. RAM usage or CPU time telemetry can be added separately from this, and showing the total wall-clock time will be a wonderful addition.

using the logs you showed above as a starting point, i imagine we would want something like...

```
Jan 28 21:42:57.618  INFO Listening on http://127.0.0.1:7878
Jan 28 21:43:04.845  INFO request{id=0}: handling request GET http://127.0.0.1:7878/
Jan 28 21:43:04.855  INFO request{id=0}: request completed using 1.4 MB of WebAssembly heap
Jan 28 21:43:04.865  INFO request{id=0}: request completed in 120ms
```

in terms of code, the logic for this will be shaped like...

```rust
let start_time = Instant::now();
// run the Wasm binary
let wall_clock_time = Instance::now().duration_since(start_time);
tracing::info("WebAssembly program completed in {}ms", wall_clock_time.as_millis());
```

i hope that's helpful, the link in my comment [above](https://github.com/fastly/Viceroy/issues/76#issuecomment-1021567901) contains a link to where we'll want to add this logic.

finally, thank you so much for taking this on @djKooks :love_letter:

**Comment by djKooks** [comment]
Hello @cratelyn . Thanks for the guide.
I've updated PR for this, so could you check when available? 🙏 
https://github.com/fastly/Viceroy/pull/121

**Comment by djKooks** [comment]
@cratelyn please close this if it's okay. Also if there's some issue in minor priority, please suggest 🙏

**Comment by cratelyn** [comment]
of course! i just tagged you over in #23, which may be a good issue to tackle next. :heart_decoration: 

with that, i'm going to close this issue!
