### ISSUE TITLE
Backend requests to TLS origins don't seem to set Host overrides properly

### ISSUE THREAD

**Issue by vespa59** [fastly/Viceroy#89]
A customer reported that, starting with version 0.42.0 (and untested in a more recent version), host overrides specified via either the `local_server.backends` block of `fastly.toml`... 

```
[local_server]
    [local_server.backends]
        [local_server.backends.www]
            url = "https://plus.stellar.example.com/"
            override_host = "plus.stellar.example.com"
```

...or via the `.with_header` property of `req`...

```
    req.set_pass(true);
        return Ok(req
        .with_path("/health-check")
        .with_header("host","plus.stellar.example.com")
        .send(BACKEND_NAME)?);
        },
    }
```

...will not be set as the `Host` for the request to the backend. Instead, it seems to be preserving the host from the incoming request (i.e. `127.0.0.1:7676`), including scenarios where the client explicitly overrides the `Host` header (i.e. `-H "Host: www.example.com"` with curl). We do seem to set the SNI host properly though. When the origin is a non-TLS host, everything seems to work fine. Also works fine in the XQD environment. 

The customer's origin is an Amazon ELB and they shared the following logs. These have been heavily redacted so the only fields included are `elb_status_code`, `"request"`, and `"domain_name"`, as defined by [Amazon's access log format](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html#access-log-entry-syntax). Note that `"domain_name"` refers to SNI. I've also anonymized their domain: 

1) Failed call to local with no host header but with `override_host` set in local server backend config:
`curl -sv -H 'Authorization: 1234567890' localhost:7676/foo.`
================== ELB log entry ===========================
`404 "GET https://localhost:443/health-check HTTP/2.0" "plus.stellar.example.com" `

2) Successful call on same local using host header:
`curl -sv -H 'Authorization: 1234567890' -H 'host: plus.stellar.example.com' localhost:7676/foo`
================== ELB log entry ===========================
`200 "GET https://plus.stellar.example.com:443/health-check HTTP/2.0" "plus.stellar.example.com"`

The `local_server` section of `fastly.toml` is configured as in the above example. For the first request, the host should have been overridden with `plus.stellar.example.com` but it appears to have been set as `localhost`, as with the original incoming request, but with the port changed out. For the second request, the host header on the original incoming client request appears to have been copied to the backend request. In both cases, the SNI domain was set as expected. 

The first request received a `404`, presumably because the ELB uses Host to match the request to a bucket. 

I've been able to repro this using a Node project on Glitch.com as an origin. The [Node script](https://glitch.com/edit/#!/quixotic-clammy-jeep?path=server.js%3A70%3A5) just echoes your `Host` back to you (if the method is `GET` and the path is `/health-check`) and logs the request on its side. When I used this origin without TLS, everything worked as expected; I saw the expected output on the client side and the request was in my logs on Glitch. When I switched to https for the backend, I didn't see the request logged on the Glitch side, and on the client side, the output was the same as if you connected to Glitch with a Host header that didn't match any service on their side, such as `localhost:7676`. 

If needed, I can get together with someone on Zoom and walk through some repros with the Glitch origin.

**Comment by aturon** [comment]
Can you share what you used for your C@E service for this reproduction?

Here's the flow in general with `Host` headers in local testing, which should match production C@E:

* The incoming request will show up as having a `Host` header that matches the host in its URL, which will appear in "absolute" form.
* Outgoing requests will determine their host header as follow:
    * Use the override host if provided by the backend
    * Otherwise, use the `Host` header on the outbound request, if provided
    * Otherwise, determine the `Host` from the URL of the backend

I have verified this behavior, including over https, with a test service using httpbin as the backend (to echo back the request headers).

**Comment by vespa59** [comment]
My origin is `quixotic-clammy-jeep.glitch.me`, and you can see the source/logs for it [here](https://glitch.com/edit/#!/quixotic-clammy-jeep?path=server.js%3A71%3A34). A successful request to `/health-check` will echo your headers back to you and will log the request on the server side. 

Here's the pertinent code for my project: 

main.rs: 
```
use fastly::http::{header, Method, StatusCode};
use fastly::{mime, Error, Request, Response};

const BACKEND_NAME: &str = "www";

#[fastly::main]
fn main(mut req: Request) -> Result<Response, Error> {
    match req.get_path() {
    // default route - straight passthru to backend
    _ => {
    req.set_pass(true);
        return Ok(req
        .with_path("/health-check")
        .send(BACKEND_NAME)?);
        },
    }
}
```

fastly.toml:
```
# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["steve+cepair@fastly.com"]
description = "A basic starter kit that demonstrates routing, simple synthetic responses and overriding caching rules."
language = "rust"
manifest_version = 2
name = "header_test"
service_id = ""
[local_server]
    [local_server.backends]
        [local_server.backends.www]
            url = "https://quixotic-clammy-jeep.glitch.me/"
            override_host = "quixotic-clammy-jeep.glitch.me"
```

The response to a curl through the local-served C@E service looks like this: 

```
curl http://localhost:7676/
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /health-check</pre>
</body>
</html>
```

which is the same as you get if you try to curl direct to glitch's IP with a `host` header of `Host: localhost` (which is what I suspect we are sending): 

```
bash$ curl -sv https://35.172.196.51/health-check -H "host: localhost:7676" -k
*   Trying 35.172.196.51:443...
* TCP_NODELAY set
* Connected to 35.172.196.51 (35.172.196.51) port 443 (#0)
* ALPN, offering http/1.1
* WARNING: disabling hostname validation also disables SNI.
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: glitch.com
* Server certificate: Amazon
* Server certificate: Amazon Root CA 1
> GET /health-check HTTP/1.1
> Host: localhost:7676
> User-Agent: curl/7.67.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Date: Wed, 03 Nov 2021 22:06:33 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 151
< Connection: keep-alive
< x-powered-by: Express
< content-security-policy: default-src 'self'
< x-content-type-options: nosniff
<
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot GET /health-check</pre>
</body>
</html>
* Connection #0 to host 35.172.196.51 left intact
* ```

Note that if I change the origin from: 

`url = "https://quixotic-clammy-jeep.glitch.me/"`

to

`url = "http://quixotic-clammy-jeep.glitch.me/"`

then it all works fine.


I noticed that httpbin will answer regardless of what you send for a 'Host': 

```
bash$ curl https://httpbin.org/headers -k -H "host: www.example.com"
{
  "headers": {
    "Accept": "*/*",
    "Host": "www.example.com",
    "User-Agent": "curl/7.67.0",
    "X-Amzn-Trace-Id": "Root=1-618aac6e-308d84c30e98a00c2d1f2190"
  }
}
```

...so I think using that for an origin won't faithfully reproduce the problem, unfortunately.
