### ISSUE TITLE
Allow host overrides in TOML configuration

### ISSUE THREAD

**Issue by cratelyn** [fastly/Viceroy#9]
One option exposed in Fastly's management UI is the ability to provide an "_override host._" See [this guide](https://docs.fastly.com/en/guides/specifying-an-override-host) for more information. The core premise is that the `host` header will be rewritten with a _different_ host than is in the outbound URL.

We should expose a setting in our TOML schema to do the same thing when running a program locally.

**Comment by aturon** [comment]
@fgsch plans to take this on!

Some notes:
* Backend configuration is defined [here](https://github.com/fastly/Viceroy/blob/813b076da9e1b5a7ed1f615ee80ffeeaac8c2cff/lib/src/config/backends.rs#L9-L12), and deserialized [here](https://github.com/fastly/Viceroy/blob/813b076da9e1b5a7ed1f615ee80ffeeaac8c2cff/lib/src/config/backends.rs#L82-L94).
  * Feel free to choose a new key to sit beside `url` for the optional override host.
* We already do [some surgery on URLs when making backend requests](https://github.com/fastly/Viceroy/blob/813b076da9e1b5a7ed1f615ee80ffeeaac8c2cff/lib/src/upstream.rs#L60-L87). That's probably where this host override logic should go.

**Comment by cratelyn** [comment]
I think this issue is done. Thanks again Federico!
