### ISSUE TITLE
Viceroy sending `Transfer-Encoding: chunked` request header with no request body causing 400 errors

### ISSUE THREAD

**Issue by smaeda-ks** [fastly/Viceroy#96]
With Viceroy, we see it’s sending either `Content-Length: 0` (for non-TLS backend) or `Transfer-Encoding: chunked` (for TLS backend) request header even if there’s no request body set and method is GET, for example.

This seems to be an inconsistent behavior between our real edge vs local instance, and it makes us hard to test TLS backends in some cases. Someone noticed that Google Cloud Run instance refuses such connections (TLS, GET with `Transfer-Encoding: chunked`) and local requests result in 400 errors when testing with Viceroy.

```toml
[local_server]
  [local_server.backends]
    [local_server.backends.backend_1]
      override_host = "httpbin.org"
      url = "https://httpbin.org/"
```

```rs
    let bereq = Request::get("https://httpbin.org/anything");
    let beresp = bereq.send("backend_1").unwrap();

    println!("RESP: {:?} ", beresp);
    Ok(beresp)
```

in the above simple example, I’m using `https://httpbin.org/anything` endpoint so that we can see what headers are sent by Viceroy. And you should see `Transfer-Encoding: chunked` in your curl response when sending a request to your local instance.

https://datatracker.ietf.org/doc/html/rfc7230#section-3.3.3

```
  3.  If a Transfer-Encoding header field is present and the chunked
       transfer coding (Section 4.1) is the final encoding, the message
       body length is determined by reading and decoding the chunked
       data until the transfer coding indicates the data is complete.

       If a Transfer-Encoding header field is present in a response and
       the chunked transfer coding is not the final encoding, the
       message body length is determined by reading the connection until
       it is closed by the server.  If a Transfer-Encoding header field
       is present in a request and the chunked transfer coding is not
       the final encoding, the message body length cannot be determined
       reliably; the server MUST respond with the 400 (Bad Request)
       status code and then close the connection.
```

What’s the best way to mitigate this? Are there any workarounds? It seems Viceroy doesn't work well with Cloud Run backends at least, for this reason.

Thank you

**Comment by aturon** [comment]
Thanks for this report. I've reproduced with the instructions you gave. I don't yet have a workaround, but suspect this may be related to #91. I'll continue to investigate and keep you posted.

**Comment by aturon** [comment]
OK, I've confirmed this is indeed another side-effect of #91. I will work on a fix for that issue.

**Comment by smaeda-ks** [comment]
Thank you, @aturon !

**Comment by aturon** [comment]
I've confirmed that https://github.com/fastly/Viceroy/pull/100 will fix it. We'll put out a new release once that lands.
