### ISSUE TITLE
Does C@E support websockets?

### ISSUE THREAD

**Issue by StarpTech** [fastly/Viceroy#98]
As titled. I couldn't find anything online. Thanks.

**Comment by aspires** [comment]
@StarpTech Not at the moment (nor do our VCL services support websockets at the time of this comment) but it's something we're exploring. 

We can keep this issue unlocked in case there are specific use cases that the community would like to log in the thread. Emailing support@fastly.com is our most preferred way for tracking feature requests, but we'll include this in the process as well.

**Comment by StarpTech** [comment]
My question is: How can we implement real-time features with C@E? Besides websockets. is it possible to use SSE over HTTP2?

**Comment by StarpTech** [comment]
I'm also a bit lost of how fastly will position itself in the near future. It feels like C@E is years behind Cloudflare Workers (with some exceptions). Could you provide any details? Asking that question here is a bit misleading but that outlines another issue. There is no official fastly discord or slack. Thank you.

**Comment by aspires** [comment]
Regarding SSE, it is possible to use Fastly to accelerate events. This blog outlining the process is a bit old, but it may help you get started. https://www.fastly.com/blog/server-sent-events-fastly

As for strategy and plans, you can email me at austin@fastly.com, and I can add you to a slack room for users. We're looking at better public collaboration options, but when we ran public chat rooms in the past, there was a lot to be desired in the experience, so looking at more structured mediums than slack/discord.

**Comment by StarpTech** [comment]
Thanks @aspires

**Comment by StarpTech** [comment]
I'm going to close it the primary question was answered. I think we don't need to elaborate on the use case of WebSockets.
