### ISSUE TITLE
Who maintains this repository?

### ISSUE THREAD

**Issue by StarpTech** [fastly/Viceroy#99]
Hi, there have been several open issues without notice to the maintainers for more than seven days. Is this repository actively maintained for the community? If not, I can lower my expectations. Thanks.

**Comment by aturon** [comment]
@StarpTech this repo is intended primarily as a development workspace for the Compute@Edge engineers who work on Viceroy, and others who would like to contribute to development; the issue tracker here is not intended as a primary support venue with availability over holidays etc.

If you have issues with C@E local testing, please use Fastly's support process, e.b. by emailing support@fastly.com, where support staff can provide a guarantee of responsiveness and work with engineers to prioritize work.

Thank you.
